studio/app/urls.py
from app.views import *
from django.urls import path


urlpatterns = [
    # path('', home, name='home'),
    path('', CardList.as_view(), name='home'),
]

studio/studio/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

studio/app/models.py
import random
import string
from django.db import models

# Create your models here.

def generate_unique_alphanumeric(length):
    """Generate a unique and random alphanumeric string of specified length."""
    characters = string.ascii_letters + string.digits
    return ''.join(random.choice(characters) for _ in range(length))


class Card(models.Model):
    c_id = models.CharField(max_length=2 , unique=True, default=generate_unique_alphanumeric(2))
    name = models.CharField(max_length=50)
    description = models.TextField(max_length=200)
    img = models.ImageField(upload_to='static/images', null=True)

studio/app/views.py
from django.shortcuts import render
from django.views.generic import ListView

from app.models import Card

# Create your views here.

# def home(request):
#     return render(request, 'home.html')

class CardList(ListView):
    queryset = Card.objects.all()
    template_name = 'home.html'

studio/app/templates/home.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Shanchvi</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="/static/css/style.css" rel="stylesheet" />
  </head>
  <body>
    <div>
      <div class="navbar">
        <div class="hamburger" onclick="toggleMenu()">
          <div></div>
          <div></div>
          <div></div>
        </div>
        <div class="navbar-left">
          <ul class="nav-links" id="nav-links">
            <li><a href="#">Home</a></li>
            <li class="dropdown">
              <a href="#">Shop</a>
              <ul class="dropdown-content">
                <li><a href="#">Birthday</a></li>
                <li><a href="#">Casual</a></li>
                <li><a href="#">Party</a></li>
                <li><a href="#">Ethnic</a></li>
                <li><a href="#">Accessories</a></li>
                <li><a href="#">Themed</a></li>
              </ul>
            </li>
            <li><a href="#">Contact</a></li>
            <li><a href="#">About Us</a></li>
            <li><a href="#">Terms & conditions</a></li>
          </ul>
        </div>
        <div class="navbar-right">
          <ul class="nav-icons">
            <li>
              <a href="#"><i class="fas fa-shopping-cart"></i></a>
            </li>
            <li>
              <a href="#"><i class="fas fa-search"></i></a>
            </li>
            <li>
              <a href="#"><i class="fas fa-sign-in-alt"></i></a>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div>
      <div
        class="main-window"
        style="position: relative; height: 100vh; overflow: hidden"
      >
        <video
          src="static/videos/Video12.mp4"
          autoplay
          loop
          muted
          style="width: 100%; height: 100%; object-fit: cover"
        ></video>
      </div>
      
    <!-- Animated card -->

      <div class="box-container">
        {% for c in card_list %}
        <div class="box-item">
          <div class="flip-box medium">
            <div class="flip-box-front text-center" style="background-image: url('{{c.img}}');">
              <div class="inner color-white">
                <h3 class="flip-box-header">{{c.name}}</h3>
                <p>{{c.description}}</p>
                <img src="https://s25.postimg.cc/65hsttv9b/cta-arrow.png" width="25px" height="25px" alt="" class="flip-box-img">
              </div>
            </div>
            <div class="flip-box-back text-center" style="background-image: url('{{c.img}}');">
              <div class="inner color-white">
                <h3 class="flip-box-header">{{c.name}}</h3>
                <p>{{c.description}}</p>
                <button class="flip-box-button">Shop Now</button>
              </div>
            </div>
          </div>
        </div>
      {% empty %}
      <h1>No cards available</h1>
      {% endfor %}
    </div> 

    <script>
      function toggleMenu() {
        var navLinks = document.getElementById("nav-links");
        navLinks.classList.toggle("active");
      }
    </script>
  </body>
</html>